spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native

server:
  port: 8888

#查看SecurityAutoConfiguration发下默认用户名为user #org.springframework.boot.autoconfigure.security.SecurityProperties.User.name
security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD}