logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
#ResourceServerProperties
security:
  oauth2:
    resource:
      user-info-uri: http://auth-service/uaa/users/current
      #user-info-uri: http://auth-service:5000/uaa/users/current
      #改为通过eureka查找服务调用

spring:
  rabbitmq:
    host: rabbitmq